#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-JSEncrypt
Version  : 2.0.0.2
Release  : 8
URL      : https://pypi.python.org/packages/source/X/XStatic-JSEncrypt/XStatic-JSEncrypt-2.0.0.2.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-JSEncrypt/XStatic-JSEncrypt-2.0.0.2.tar.gz
Summary  : JSEncrypt 2.0.0 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-JSEncrypt-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-JSEncrypt
--------------
JSEncrypt JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-JSEncrypt package.
Group: Default

%description python
python components for the XStatic-JSEncrypt package.


%prep
%setup -q -n XStatic-JSEncrypt-2.0.0.2

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
