#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-JSEncrypt
Version  : 2.3.1.1
Release  : 16
URL      : http://pypi.debian.net/XStatic-JSEncrypt/XStatic-JSEncrypt-2.3.1.1.tar.gz
Source0  : http://pypi.debian.net/XStatic-JSEncrypt/XStatic-JSEncrypt-2.3.1.1.tar.gz
Summary  : JSEncrypt 2.3.1 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-JSEncrypt-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
XStatic-JSEncrypt
--------------
JSEncrypt JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-JSEncrypt package.
Group: Default
Provides: xstatic-jsencrypt-python

%description python
python components for the XStatic-JSEncrypt package.


%prep
%setup -q -n XStatic-JSEncrypt-2.3.1.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1488596434
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1488596434
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
